version: "3.7"
services:
    db:
        image: postgres:15.1-alpine
        restart: always
        environment:
            POSTGRES_DB: jpslot-test
            POSTGRES_USER: mike
            POSTGRES_PASSWORD: 123456
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
  
volumes:
    db-data: